### ISSUE TITLE
Update the links of the JS, CSS and Image files in all the test.html files(except test1.html)

### ISSUE THREAD

**Issue by rajat2502** [NJACKWinterOfCode/Physics-quiz#11]

**Comment by ExpressHermes** [comment]
I would like to do this.

**Comment by rajat2502** [comment]
Okay assigning it to you but please do check before making a pr that all the js and CSS are linked and working properly

**Comment by sgpritam** [comment]
I would like to do this @rajat2502

**Comment by rajat2502** [comment]
@ExpressHermes are you working on it or should I assign it to somebody else?

**Comment by sgpritam** [comment]
I want to work on this issues

**Comment by sakshamj74** [comment]
I would like to work on this @rajat2502

**Comment by sakshamj74** [comment]
@rajat2502 Plz help regarding this.Not able to figure out what to do.

**Comment by rajat2502** [comment]
you have to update all the links of all CSS, js, and Images in all test.html files. For reference, you can have a look at the file name test1.html. Those files are not linked properly because of which the js and CSS of those HTML pages are not loading.
See the changes in https://github.com/NJACKWinterOfCode/Physics-quiz/commit/fb7f910e1a54ff3656a59084d6e3b9a3107aec29.
You have to do exactly the same changes in all other test.html files (except test1.html which is already updated)

**Comment by sakshamj74** [comment]
Thanks @rajat2502 .Please review #24

**Comment by rajat2502** [comment]
Done!!!
