### ISSUE TITLE
Need a login form

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/Physics-quiz#13]
When user click on avatar then open pop up window for the login form

I'll like to work on this.
![1](https://user-images.githubusercontent.com/41269164/69931208-6bb3bc00-14ec-11ea-9e7e-ff5c9c32f9d4.PNG)

**Comment by sgpritam** [comment]
@rajat2502 Please review

**Comment by rajat2502** [comment]
We don't need that right now
