### ISSUE TITLE
Adding hyperlink to college website in contact.html

### ISSUE THREAD

**Issue by sakshamj74** [NJACKWinterOfCode/Physics-quiz#25]
![njack_1](https://user-images.githubusercontent.com/43048913/70341907-f8a69e80-1879-11ea-94cf-1e8f009e5765.png)
Adding a hyperlink to college website where college name is written

**Comment by sakshamj74** [comment]
@rajat2502 Can I work on this.

**Comment by rajat2502** [comment]
Not required for now.
