### ISSUE TITLE
Improve visibility of welcome text in landing page(index.html)

### ISSUE THREAD

**Issue by charan7386** [NJACKWinterOfCode/Physics-quiz#5]
"**WELCOME TO THE PHYSICS TEST**" heading in index.html is not clearly visible due to background image.

**Comment by rajat2502** [comment]
Please provide an appropriate description to the issue

**Comment by sgpritam** [comment]
I would like to work on this.

**Comment by Darshilp326** [comment]
i would like to work on this.

**Comment by sakshamj74** [comment]
please review my pr #15 tried to fix the issue
